version: '3.9'
services:
  app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
    entrypoint: /app/run.sh
    depends_on:
      - db
      - mailhog

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: golodging
      POSTGRES_PASSWORD: golodging
      POSTGRES_DB: golodging
    ports:
      - '5432:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  mailhog:
    image: 'jcalonso/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"
    deploy:
      mode: replicated
      replicas: 1